name: "check-links"

on:
    push:
    schedule:
        - cron: "13 9 * * 1"

jobs:
    markdown-link-check:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@master
            - uses: gaurav-nelson/github-action-markdown-link-check@v1
